# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc.protos import ml_service_pb2 as app_dot_grpc_dot_protos_dot_ml__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/grpc/protos/ml_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealthServiceStub(object):
    """Health Check
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/mlservice.HealthService/Check',
                request_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """Health Check
    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.HealthRequest.FromString,
                    response_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlservice.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mlservice.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """Health Check
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.HealthService/Check',
            app_dot_grpc_dot_protos_dot_ml__service__pb2.HealthRequest.SerializeToString,
            app_dot_grpc_dot_protos_dot_ml__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DatasetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDatasets = channel.unary_unary(
                '/mlservice.DatasetService/ListDatasets',
                request_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.ListDatasetsRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.ListDatasetsResponse.FromString,
                _registered_method=True)
        self.UploadDataset = channel.unary_unary(
                '/mlservice.DatasetService/UploadDataset',
                request_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.UploadDatasetRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.UploadDatasetResponse.FromString,
                _registered_method=True)


class DatasetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatasetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.ListDatasetsRequest.FromString,
                    response_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.ListDatasetsResponse.SerializeToString,
            ),
            'UploadDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDataset,
                    request_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.UploadDatasetRequest.FromString,
                    response_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.UploadDatasetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlservice.DatasetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mlservice.DatasetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatasetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.DatasetService/ListDatasets',
            app_dot_grpc_dot_protos_dot_ml__service__pb2.ListDatasetsRequest.SerializeToString,
            app_dot_grpc_dot_protos_dot_ml__service__pb2.ListDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.DatasetService/UploadDataset',
            app_dot_grpc_dot_protos_dot_ml__service__pb2.UploadDatasetRequest.SerializeToString,
            app_dot_grpc_dot_protos_dot_ml__service__pb2.UploadDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModelServiceStub(object):
    """-------------------- Model Service --------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListModelClasses = channel.unary_unary(
                '/mlservice.ModelService/ListModelClasses',
                request_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.ListModelClassesRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.ListModelClassesResponse.FromString,
                _registered_method=True)
        self.TrainModel = channel.unary_unary(
                '/mlservice.ModelService/TrainModel',
                request_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.TrainModelRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.TrainModelResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/mlservice.ModelService/ListModels',
                request_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/mlservice.ModelService/Predict',
                request_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.Retrain = channel.unary_unary(
                '/mlservice.ModelService/Retrain',
                request_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.RetrainRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.RetrainResponse.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/mlservice.ModelService/DeleteModel',
                request_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.DeleteModelResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """-------------------- Model Service --------------------
    """

    def ListModelClasses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListModelClasses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModelClasses,
                    request_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.ListModelClassesRequest.FromString,
                    response_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.ListModelClassesResponse.SerializeToString,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.TrainModelRequest.FromString,
                    response_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.TrainModelResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.ListModelsRequest.FromString,
                    response_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.ListModelsResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.PredictRequest.FromString,
                    response_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.PredictResponse.SerializeToString,
            ),
            'Retrain': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrain,
                    request_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.RetrainRequest.FromString,
                    response_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.RetrainResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.DeleteModelRequest.FromString,
                    response_serializer=app_dot_grpc_dot_protos_dot_ml__service__pb2.DeleteModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlservice.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mlservice.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """-------------------- Model Service --------------------
    """

    @staticmethod
    def ListModelClasses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.ModelService/ListModelClasses',
            app_dot_grpc_dot_protos_dot_ml__service__pb2.ListModelClassesRequest.SerializeToString,
            app_dot_grpc_dot_protos_dot_ml__service__pb2.ListModelClassesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.ModelService/TrainModel',
            app_dot_grpc_dot_protos_dot_ml__service__pb2.TrainModelRequest.SerializeToString,
            app_dot_grpc_dot_protos_dot_ml__service__pb2.TrainModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.ModelService/ListModels',
            app_dot_grpc_dot_protos_dot_ml__service__pb2.ListModelsRequest.SerializeToString,
            app_dot_grpc_dot_protos_dot_ml__service__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.ModelService/Predict',
            app_dot_grpc_dot_protos_dot_ml__service__pb2.PredictRequest.SerializeToString,
            app_dot_grpc_dot_protos_dot_ml__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.ModelService/Retrain',
            app_dot_grpc_dot_protos_dot_ml__service__pb2.RetrainRequest.SerializeToString,
            app_dot_grpc_dot_protos_dot_ml__service__pb2.RetrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlservice.ModelService/DeleteModel',
            app_dot_grpc_dot_protos_dot_ml__service__pb2.DeleteModelRequest.SerializeToString,
            app_dot_grpc_dot_protos_dot_ml__service__pb2.DeleteModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
