apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: mlhw
type: Opaque
data:
  accesskey: bWluaW8=        # "minio" в base64
  secretkey: bWluaW8xMjM=    # "minio123" в base64

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: mlhw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - "--console-address"
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: accesskey
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secretkey
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          emptyDir: {}   # для учебного задания достаточно

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: mlhw
spec:
  type: NodePort
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 32000
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 32001
  selector:
    app: minio